# Generated by Django 2.1.3 on 2024-12-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.AddField(
            model_name='pago',
            name='estadoPago',
            field=models.BooleanField(default=False, help_text='Indica si el pago está pagado (True) o no pagado (False)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
